agents:
  enable_code_generation: true
  enable_command_execution: false
  max_agents: 10
database:
  echo: true
  url: sqlite:///data/dev_ollama_flow.db
debug: true
llm:
  default_model: llama3
  enable_caching: true
  max_model_size_gb: 5.5
  request_timeout: 300
logging:
  level: DEBUG
performance:
  database_poll_interval: 1.0
  enable_async_db: true
  enable_request_batching: true
security:
  enable_command_whitelist: true
  max_command_timeout: 60
